# file: docker-compose.yml
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint: [ "sh", "-lc" ]
    command:
      - >
        anvil --host 0.0.0.0
              --fork-url ${RPC_MAINNET}
              --fork-block-number ${FORK_BLOCK}
    ports:
      - "8545:8545"
    environment:
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
      # (keep your other envs here or use env_file)
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 5s
      timeout: 3s
      retries: 50
      start_period: 10s
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      anvil:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Force the bot to use the Anvil container URL (overrides value from .env)
      RPC_MAINNET: http://anvil:8545
    restart: unless-stopped