services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: |
      anvil --host 0.0.0.0 \
            --fork-url ${RPC_MAINNET} \
            --fork-block-number ${FORK_BLOCK}
    ports:
      - "8545:8545"
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - anvil
    env_file:
      - .env
